version: "3.3"
services:
  api-student-list:
    image: sadofrazer/api-student-list:v1
    ports:
      - "8080:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json

  web_site:
    image: php:apache
    depends_on:
      - api-student-list
    volumes:
      - ./website:/var/www/html
    ports:
      - "80:80"
    environment:
      - USERNAME=toto 
      - PASSWORD=python
      - API_NAME=api-student-list
      - API_PORT=5000
      
volumes:
  db-data:
