version: "3.3"
services:

  api-student-list:
    image: sadofrazer/api-student-list:v1
    ports:
      - "8080:5000"
    volumes:
      - db-data:/data/

  web_site:
    image: php:apache
    depends_on:
      - api-student-list
    volumes:
      - ./website:/var/www/html
    ports:
      - "80:80"
    environment:
      - USERNAME=toto 
      - PASSWORD=python
      - API_NAME=student-list_api-student-list_1
      - API_PORT=5000
      
volumes:
  db-data: